CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
login VARCHAR(255) NOT NULL UNIQUE,
birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description VARCHAR(255),
release_date DATE NOT NULL,
duration INT NOT NULL,
mpa_id INT,
FOREIGN KEY (mpa_id) REFERENCES mpa(id),
genre_id INT,
FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE IF NOT EXISTS mpa (
id INT PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
id INT PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre (
film_id INT,
genre_id INT,
FOREIGN KEY (film_id) REFERENCES films(id),
FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE IF NOT EXISTS likes (
film_id INT,
user_id INT,
FOREIGN KEY (film_id) REFERENCES films(id),
FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS FRIENDS (
USER_ID INTEGER REFERENCES USERS (id) ON DELETE CASCADE,
FRIEND_ID INTEGER REFERENCES USERS (id) ON DELETE CASCADE,
PRIMARY KEY (USER_ID, FRIEND_ID)
);